---
language: ruby
sudo: false
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails_4_2_sprockets_rails_2.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0_sprockets_rails_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1_sprockets_rails_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2_sprockets_rails_2.gemfile
  - gemfiles/rails_5_2.gemfile
before_install: gem update --system && gem install bundler # remove this once it isn't required by Travis due to Rubygems / Bundler version incompatibilities related to travis-ci/travis-ci#9333
script: bundle exec rspec spec
matrix:
  fast_finish: true
