---
language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - ruby-head
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_edge.gemfile
script: bundle exec rspec spec
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
