---
language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2_sprockets_rails_2_sprockets_2.gemfile
  - gemfiles/rails_4_2_sprockets_rails_2.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
script: bundle exec rspec spec
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails_5_0.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_5_0.gemfile
