---
language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
gemfile:
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2_sprockets_2.gemfile
  - gemfiles/rails_4_2_sprockets_3.gemfile
script: bundle exec rspec spec
matrix:
  fast_finish: true
