---
language: ruby
sudo: false
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/rails_4_2_sprockets_rails_2.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0_sprockets_rails_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1_sprockets_rails_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2_sprockets_rails_2.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0_sprockets_rails_2.gemfile
  - gemfiles/rails_6_0.gemfile
before_install: # use Bundler 1.x across all matrix combinations (Rails 4.2 doesn't support Bundler 2+)
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - bundle version
script: bundle exec rspec spec
matrix:
  exclude:
  - rvm: 2.4.6
    gemfile: gemfiles/rails_6_0_sprockets_rails_2.gemfile
  - rvm: 2.4.6
    gemfile: gemfiles/rails_6_0.gemfile
  fast_finish: true
